language: node_js
node_js:
- 8.9.0
dist: trusty
git:
  depth: false
jobs:
  include:
    - stage: "Fundamental-react: Lint"
      script: npm run lint
    - stage: "Fundamental-react: Test"
      name: "Unit tests"
      script: npm run test:coverage
notifications:
  email:
    on_failure: always
    on_success: change
before_deploy:
- bash ./ci-scripts/setup_npm.sh
deploy:
  - provider: script
    script: bash ./ci-scripts/publish.sh $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER
    on:
      branch: master
    skip_cleanup: true