language: node_js
node_js: 10.15.0
dist: trusty
git:
  depth: false
script:
  - npm run build
jobs:
  include:
  - stage: "Fundamental-react: Test & Lint"
    script: npm run lint && npm run test:coveralls
  - stage: Deploy
    if: branch = master AND type != pull_request
    before_deploy:
    - bash ./ci-scripts/setup_npm.sh
    deploy:
      - provider: script
        script: bash ./ci-scripts/publish.sh $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER
        skip_cleanup: true
notifications:
  email:
    on_failure: always
    on_success: change
  slack: 
    rooms:
      - ui-fundamentals:zVRyxlqkYnQFD7p8QHkWM8Fd#react-automated