language: node_js
node_js:
- 8.9.0
dist: trusty
git:
  depth: false
jobs:
  include:
    - stage: "Fundamental-react: Lint"
      script: npm run lint
    - stage: "Fundamental-react: Test"
      name: "Unit tests"
      script: npm run test:coverage
    - stage: deploy
      if: branch = master AND type != pull_request
      before_deploy:
      - bash ./ci-scripts/setup_npm.sh
      deploy:
        - provider: script
          script: bash ./ci-scripts/publish.sh $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER
          skip_cleanup: true
notifications:
  email:
    on_failure: always
    on_success: change