language: node_js
node_js:
- 8.9.0
dist: trusty
git:
  depth: false
branches:
  only:
  - develop
  - "/^feature\\/.*$/"
  - "/^fix\\/.*$/"
jobs:
  include:
    - stage: "Fundamental-react: Lint"
      script: npm run lint
    - stage: "Fundamental-react: Test"
      name: "Unit tests"
      script: npm run test:coverage
notifications:
  email:
    on_failure: always
    on_success: change
