language: node_js
node_js:
- 8.9.0
dist: trusty
git:
  depth: false
branches:
  only:
  - develop
  - "/^feature\\/.*$/"
jobs:
  include:
    - stage: "Fundamental-react build"
      name: "Unit tests"
      script: "./ci-scripts/unit-tests.sh"
notifications:
  email:
    on_failure: always
    on_success: change
before_deploy:
  - npm run build
deploy:
  provider: script
  script: bash ./ci-scripts/publish.sh $TRAVIS_BRANCH $TRAVIS_BUILD_NUMBER
  on:
    branch: master
