language: node_js
node_js: 16.14.0
cache: npm
dist: trusty
git:
  depth: false
script:
  - npm run build
jobs:
  include:
  - stage: Lint commit message
    script: commitlint-travis
  - stage: Lint and Test
    script: npm run lint && npm run size
  -
    script: npm run test:coverage && npm run test:coveralls
  -
    script: npm run test:storybook
  - stage: Pre-release
    if: branch = main AND type != pull_request
    before_deploy:
    - git checkout main
    - bash ./ci-scripts/setup-npm.sh
    deploy:
    - provider: script
      script: bash ./ci-scripts/publish-rc.sh
      skip_cleanup: true
      on:
        all_branches: true
  - stage: Release
    if: branch = tmp_branch_for_automated_release_do_not_use
    before_deploy:
    - git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
    - git fetch
    - git checkout main
    - bash ./ci-scripts/setup-npm.sh
    deploy:
    - provider: script
      script: bash ./ci-scripts/publish.sh
      skip_cleanup: true
      on:
        all_branches: true
notifications:
  email:
    on_failure: always
    on_success: change
  slack: 
    rooms:
      - ui-fundamentals:zVRyxlqkYnQFD7p8QHkWM8Fd#react-automated
