language: node_js
node_js:
- 8.9.0
dist: trusty
git:
  depth: false
branches:
  only:
  - develop
  - "/^feature\\/.*$/"
jobs:
  include:
    - stage: "Fundamental-react: Lint"
      script: npm run lint
    - stage: "Fundamental-react: Build"
      name: "Unit tests"
      script: "./ci-scripts/unit-tests.sh"
notifications:
  email:
    on_failure: always
    on_success: change
