export const defaultPropDescriptions = {
    buttonProps: 'Additional props to be spread to the `<button>` element.',
    children: 'Node(s) to render within the component.',
    className: 'CSS class(es) to add to the element.',
    compact: 'Set to **true** to enable compact mode.',
    customStyles: 'Load custom stylesheet via require statement',
    disabled: 'Set to **true** to mark component as disabled and make it non-interactive.',
    disableStyles: 'Disable loading stylesheets from fundamental-styles.',
    glyph: 'The icon to include. See the icon page for the list of icons.',
    id: 'Value for the `id` attribute on the element.',
    inputProps: 'Additional props to be spread to the `<input>` element.',
    inputClassName: 'CSS class(es) to add to the `<input>` element.',
    labelProps: 'Additional props to be spread to the `<label>` element.',
    headingLevel: 'Heading level. `<h1>` is reserved for the page title. It should not appear in components.',
    listProps: 'Additional props to be spread to the `<ul>` element.',
    localizedText: 'Localized text to be updated based on location/language.',
    modifier: 'Sets a style variation for a modified appearance.',
    onChange: 'Callback function when the change event fires on the component.',
    onClick: 'Callback function when user clicks on the component.',
    placeholder: 'Localized placeholder text of the input.',
    popoverProps: 'Additional props to be spread to the [Popover](/popover) component.',
    readOnly: 'Set to **true** to mark component as readonly.',
    size: 'Size of the component.',
    title: 'Localized text for the heading.',
    titleProps: 'Additional props to be spread to the title\'s heading element.',
    type: 'Sets the variation of the component. Primarily used for styling.'
};
