export const STYLE_LOOKUP = {
    'ActionBar': { name: 'action-bar', fonts: true },
    'Alert': { name: 'alert', fonts: true },
    'Badge': { name: 'badge', fonts: true },
    'Breadcrumb': { name: 'breadcrumb', fonts: true },
    'Button': { name: 'button', fonts: true },
    'ButtonGroup': { name: 'button-group' },
    'Calendar': { name: 'calendar', fonts: true },
    'ComboboxInput': {},
    'ContextualMenu': {},
    'Counter': { name: 'counter', fonts: true },
    'DatePicker': {},
    'Dropdown': {},
    'Checkbox': {},
    'FormFieldset': {},
    'FormInput': {},
    'FormItem': {},
    'FormLabel': {},
    'FormLegend': {},
    'FormMessage': {},
    'FormRadioGroup': {},
    'FormRadioItem': {},
    'FormSelect': {},
    'FormSet': {},
    'FormTextarea': {},
    'Icon': {},
    'Identifier': {},
    'Image': {},
    'InlineHelp': {},
    'InputGroup': {},
    'LayoutGrid': {},
    'Label': { name: 'label', fonts: true },
    'Link': {},
    'ListGroup': {},
    'LocalizationEditor': {},
    'Menu': {},
    'Modal': {},
    'MultiInput': {},
    'Pagination': {},
    'Panel': {},
    'Popover': {},
    'SearchInput': {},
    'Shellbar': {},
    'SideNavigation': {},
    'Status': { name: 'status-label', fonts: true },
    'Table': {},
    'Tab': {},
    'TabGroup': {},
    'Tile': {},
    'Time': {},
    'TimePicker': {},
    'Toggle': {},
    'Token': {},
    'TreeView': {}
};
